// examples/svelte/examples/TagsExample.svelte
<script lang="ts">
  import Select from '../Select.svelte'

  let { theme }: { theme: 'light' | 'dark' | 'auto' } = $props()
  let tagOptions = $state<string[]>(['vue', 'react', 'svelte', 'typescript', 'rust', 'go'])
  let tags = $state<string[]>(['svelte', 'typescript'])

  function onCreate(value: string) {
    if (!tagOptions.includes(value)) tagOptions = [...tagOptions, value]
    if (!tags.includes(value)) tags = [...tags, value]
  }
</script>

<article class="card">
  <h2>Tags — create on the fly</h2>
  <p>Type and press Enter to create new options.</p>
  <Select
    modelValue={tags}
    mode="tags"
    options={tagOptions}
    taggable
    {theme}
    placeholder="Add tags"
    onChange={(v) => (tags = v as string[])}
    {onCreate}
  />
  <pre>{JSON.stringify({ tags }, null, 2)}</pre>
</article>

// examples/react/examples/TagsExample.tsx
import { useState } from 'react'
import { Select } from '@anil-labs/select-react'

export default function TagsExample({ theme }: { theme: 'light' | 'dark' | 'auto' }) {
  const [tagOptions, setTagOptions] = useState<string[]>([
    'vue',
    'react',
    'svelte',
    'typescript',
    'rust',
    'go',
  ])
  const [tags, setTags] = useState<string[]>(['react', 'typescript'])

  function onCreate(value: string) {
    setTagOptions((prev) => (prev.includes(value) ? prev : [...prev, value]))
    setTags((prev) => (prev.includes(value) ? prev : [...prev, value]))
  }

  return (
    <article className="card">
      <h2>Tags  create on the fly</h2>
      <p>Type and press Enter to create new options.</p>
      <Select
        modelValue={tags}
        mode="tags"
        options={tagOptions}
        taggable
        theme={theme}
        placeholder="Add tags"
        onChange={(v) => setTags(v as string[])}
        onCreate={onCreate}
      />
      <pre>{JSON.stringify({ tags }, null, 2)}</pre>
    </article>
  )
}
