// examples/svelte/Select.svelte
<script lang="ts" generics="T extends OptionLike = OptionLike">
  import { createSelectAdapter, toSvelteProps } from '@anil-labs/select-svelte'
  import type { OptionLike, NormalizedOption, SelectMachineConfig } from '@anil-labs/select-svelte'
  import { onMount, type Snippet } from 'svelte'

  type Props = SelectMachineConfig<T> & {
    renderOption?: Snippet<[NormalizedOption<T>, boolean, boolean]>
    renderValue?: Snippet<[NormalizedOption<T>]>
    class?: string
  }

  let { renderOption, renderValue, class: className, ...config }: Props = $props()

  const adapter = createSelectAdapter<T>(config as SelectMachineConfig<T>)

  // Manual reactivity bridge: every machine notify bumps `tick`, which is
  // the single $state cell every $derived in this component reads to know
  // it needs to recompute. Without this Svelte 5 has no way to see the
  // machine's internal mutations.
  let tick = $state(0)
  onMount(() => adapter.subscribe(() => (tick += 1)))

  // Re-push prop changes into the machine on every effect run.
  $effect(() => {
    adapter.machine.update(config as SelectMachineConfig<T>)
  })

  // $derived.by re-runs whenever any reactive read inside changes 
  // `void tick` is the explicit (lint-friendly) way to register that
  // dependency without producing an "unused expression" warning.
  const state = $derived.by(() => {
    void tick
    return adapter.machine.getState()
  })
  const filtered = $derived.by(() => {
    void tick
    return adapter.machine.getFilteredOptions()
  })
  const selected = $derived.by(() => {
    void tick
    return adapter.machine.getSelectedOptions()
  })
  const isMulti = $derived.by(() => {
    void tick
    return adapter.machine.isMulti()
  })
  const hasSelection = $derived.by(() => {
    void tick
    return adapter.machine.hasSelection()
  })

  let rootEl: HTMLDivElement | undefined = $state()
  let menuEl: HTMLDivElement | undefined = $state()
  let searchEl: HTMLInputElement | undefined = $state()

  $effect(() => {
    if (!state.isOpen) return
    function onDown(event: MouseEvent) {
      const target = event.target as Node | null
      if (!target) return
      if (rootEl?.contains(target)) return
      if (menuEl?.contains(target)) return
      adapter.machine.close()
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  })

  $effect(() => {
    if (state.isOpen && config.searchable !== false) {
      queueMicrotask(() => searchEl?.focus())
    }
  })
</script>

<div bind:this={rootEl} {...toSvelteProps(adapter.machine.getRootProps())}>
  <div class="vselect-control" {...toSvelteProps(adapter.machine.getControlProps())}>
    <div class="vselect-values">
      {#if !isMulti && selected[0] && !state.query}
        {#if renderValue}
          {@render renderValue(selected[0])}
        {:else}
          <span class="vselect-single">{selected[0].label}</span>
        {/if}
      {/if}

      {#if isMulti && selected.length > 0}
        {#each selected as option (option.id)}
          <span class="vselect-tag">
            <span class="vselect-tag-label">{option.label}</span>
            <button
              type="button"
              class="vselect-tag-remove"
              aria-label="Remove {option.label}"
              tabindex={-1}
              onmousedown={(event) => {
                event.preventDefault()
                adapter.machine.deselectOption(option)
              }}>×</button
            >
          </span>
        {/each}
      {/if}

      {#if config.searchable !== false}
        <input
          bind:this={searchEl}
          {...toSvelteProps(adapter.machine.getSearchProps())}
          class={['vselect-search', !isMulti && hasSelection && !state.query ? 'is-hidden' : '']
            .filter(Boolean)
            .join(' ')}
        />
      {/if}
    </div>

    <div class="vselect-indicators">
      {#if config.loading}
        <span class="vselect-spinner" aria-hidden="true"></span>
      {:else if config.clearable !== false && hasSelection && !config.disabled}
        <button {...toSvelteProps(adapter.machine.getClearButtonProps())} class="vselect-indicator"
          >×</button
        >
      {/if}
      <span class="vselect-indicator" aria-hidden="true">▾</span>
    </div>
  </div>

  <div bind:this={menuEl} {...toSvelteProps(adapter.machine.getMenuProps())} class="vselect-menu">
    {#if config.loading}
      <div class="vselect-loading">
        <span class="vselect-spinner"></span>
        <span>{config.loadingText ?? 'Loading…'}</span>
      </div>
    {:else if filtered.length === 0}
      <div class="vselect-empty">{adapter.machine.emptyMessage()}</div>
    {:else}
      {#each filtered as option, index (option.id)}
        {@const optProps = toSvelteProps(adapter.machine.getOptionProps(option, index))}
        <div {...optProps}>
          {#if renderOption}
            {@render renderOption(
              option,
              state.activeIndex === index,
              adapter.machine.isSelected(option),
            )}
          {:else}
            <span>{option.label}</span>
          {/if}
        </div>
      {/each}
    {/if}

    {#if adapter.machine.showCreate()}
      <div
        class="vselect-create"
        role="option"
        aria-selected={false}
        tabindex={-1}
        onmousedown={(event) => {
          event.preventDefault()
          adapter.machine.createFromQuery()
        }}
      >
        Create <strong>{state.query}</strong>
      </div>
    {/if}
  </div>
</div>

// playground/solid/Select.tsx
import { createEffect, createMemo, For, onCleanup, Show, type JSX } from 'solid-js'
import { createSelect, toSolidProps } from '@/solid'
import type {
  NormalizedOption,
  OptionLike,
  SelectMachineConfig,
} from '@/solid'

// Idiomatic Solid Select component built on the headless `createSelect`
// primitive. Solid's reactivity is fine-grained — wrapping every machine
// read in a `createMemo` keeps the JSX subscribed via `select.tick()`.
//
// This file ships with the playground as a copy-paste reference; the npm
// package itself stays headless so consumers can wire their own DOM.

export interface SolidSelectProps<T extends OptionLike = OptionLike>
  extends SelectMachineConfig<T> {
  class?: string
  renderOption?: (option: NormalizedOption<T>, isActive: boolean, isSelected: boolean) => JSX.Element
  renderValue?: (option: NormalizedOption<T>) => JSX.Element
}

export default function Select<T extends OptionLike = OptionLike>(
  props: SolidSelectProps<T>,
): JSX.Element {
  const select = createSelect<T>(props as SelectMachineConfig<T>)

  // Push every prop change into the machine. Solid re-runs the effect on
  // any reactive read inside, and `props` is reactive.
  createEffect(() => {
    select.machine.update(props as SelectMachineConfig<T>)
  })

  // All these read `select.tick()` so they re-evaluate on every notify.
  const state = createMemo(() => (select.tick(), select.machine.getState()))
  const filtered = createMemo(() => (select.tick(), select.machine.getFilteredOptions()))
  const selected = createMemo(() => (select.tick(), select.machine.getSelectedOptions()))
  const isMulti = createMemo(() => (select.tick(), select.machine.isMulti()))
  const hasSelection = createMemo(() => (select.tick(), select.machine.hasSelection()))

  let rootEl: HTMLDivElement | undefined
  let menuEl: HTMLDivElement | undefined
  let searchEl: HTMLInputElement | undefined

  // Outside-click closes the menu.
  createEffect(() => {
    if (!state().isOpen) return
    function onDown(event: MouseEvent) {
      const target = event.target as Node | null
      if (!target) return
      if (rootEl?.contains(target)) return
      if (menuEl?.contains(target)) return
      select.machine.close()
    }
    document.addEventListener('mousedown', onDown)
    onCleanup(() => document.removeEventListener('mousedown', onDown))
  })

  // Auto-focus the search on open.
  createEffect(() => {
    if (state().isOpen && props.searchable !== false) {
      queueMicrotask(() => searchEl?.focus())
    }
  })

  return (
    <div ref={rootEl} {...toSolidProps(select.machine.getRootProps())}>
      <div class="vselect-control" {...toSolidProps(select.machine.getControlProps())}>
        <div class="vselect-values">
          <Show when={!isMulti() && selected()[0] && !state().query}>
            {props.renderValue ? (
              props.renderValue(selected()[0]!)
            ) : (
              <span class="vselect-single">{selected()[0]!.label}</span>
            )}
          </Show>

          <Show when={isMulti()}>
            <For each={selected()}>
              {(option) => (
                <span class="vselect-tag">
                  <span class="vselect-tag-label">{option.label}</span>
                  <button
                    type="button"
                    class="vselect-tag-remove"
                    aria-label={`Remove ${option.label}`}
                    tabindex={-1}
                    onmousedown={(event) => {
                      event.preventDefault()
                      select.machine.deselectOption(option)
                    }}
                  >
                    ×
                  </button>
                </span>
              )}
            </For>
          </Show>

          <Show when={props.searchable !== false}>
            <input
              ref={searchEl}
              {...toSolidProps(select.machine.getSearchProps())}
              class={['vselect-search', !isMulti() && hasSelection() && !state().query ? 'is-hidden' : '']
                .filter(Boolean)
                .join(' ')}
            />
          </Show>
        </div>

        <div class="vselect-indicators">
          <Show
            when={props.loading}
            fallback={
              <Show when={props.clearable !== false && hasSelection() && !props.disabled}>
                <button
                  {...toSolidProps(select.machine.getClearButtonProps())}
                  class="vselect-indicator"
                >
                  ×
                </button>
              </Show>
            }
          >
            <span class="vselect-spinner" aria-hidden="true" />
          </Show>
          <span class="vselect-indicator" aria-hidden="true">▾</span>
        </div>
      </div>

      <div ref={menuEl} {...toSolidProps(select.machine.getMenuProps())} class="vselect-menu">
        <Show
          when={!props.loading}
          fallback={
            <div class="vselect-loading">
              <span class="vselect-spinner" />
              <span>{props.loadingText ?? 'Loading…'}</span>
            </div>
          }
        >
          <Show
            when={filtered().length > 0}
            fallback={<div class="vselect-empty">{select.machine.emptyMessage()}</div>}
          >
            <For each={filtered()}>
              {(option, index) => {
                const optProps = createMemo(() =>
                  (select.tick(), toSolidProps(select.machine.getOptionProps(option, index()))),
                )
                return (
                  <div {...optProps()}>
                    {props.renderOption
                      ? props.renderOption(
                          option,
                          state().activeIndex === index(),
                          select.machine.isSelected(option),
                        )
                      : <span>{option.label}</span>}
                  </div>
                )
              }}
            </For>
          </Show>
        </Show>

        <Show when={(select.tick(), select.machine.showCreate())}>
          <div
            class="vselect-create"
            role="option"
            aria-selected={false}
            tabindex={-1}
            onmousedown={(event) => {
              event.preventDefault()
              select.machine.createFromQuery()
            }}
          >
            Create <strong>{state().query}</strong>
          </div>
        </Show>
      </div>
    </div>
  )
}
