// playground/vue/examples/BasicExample.vue
<script setup lang="ts">
import { ref } from 'vue'
import { VSelect } from '@/vue'
import { fruits } from '../../shared/data'

defineProps<{ theme: 'light' | 'dark' | 'auto' }>()

const fruit = ref<string | null>(null)
</script>

<template>
  <article class="card">
    <h2>Single — primitives</h2>
    <p>Pass an array of strings; v-model binds the chosen value.</p>
    <VSelect v-model="fruit" :options="fruits" :theme="theme" placeholder="Pick a fruit" />
    <pre>{{ JSON.stringify({ fruit }, null, 2) }}</pre>
  </article>
</template>

// examples/svelte/examples/BasicExample.svelte
<script lang="ts">
  import Select from '../Select.svelte'
  import { fruits } from '../../shared/data'

  let { theme }: { theme: 'light' | 'dark' | 'auto' } = $props()
  let fruit = $state<string | null>(null)
</script>

<article class="card">
  <h2>Single — primitives</h2>
  <p>Pass an array of strings; modelValue is two-way through onChange.</p>
  <Select
    modelValue={fruit}
    options={fruits}
    {theme}
    placeholder="Pick a fruit"
    onChange={(v) => (fruit = v as string | null)}
  />
  <pre>{JSON.stringify({ fruit }, null, 2)}</pre>
</article>
