// playground/vue/examples/TagsExample.vue
<script setup lang="ts">
import { ref } from 'vue'
import { VSelect } from '@/vue'

defineProps<{ theme: 'light' | 'dark' | 'auto' }>()

const tags = ref<string[]>(['vue', 'typescript'])
const tagOptions = ref<string[]>(['vue', 'react', 'svelte', 'typescript', 'rust', 'go'])

function onCreateTag(value: string) {
  if (!tagOptions.value.includes(value)) tagOptions.value.push(value)
  tags.value = [...tags.value, value]
}
</script>

<template>
  <article class="card">
    <h2>Tags — create on the fly</h2>
    <p>Type and press Enter to create new options.</p>
    <VSelect
      v-model="tags"
      mode="tags"
      :options="tagOptions"
      taggable
      :theme="theme"
      placeholder="Add tags"
      @create="onCreateTag"
    />
    <pre>{{ JSON.stringify({ tags }, null, 2) }}</pre>
  </article>
</template>

// examples/svelte/examples/TagsExample.svelte
<script lang="ts">
  import Select from '../Select.svelte'

  let { theme }: { theme: 'light' | 'dark' | 'auto' } = $props()
  let tagOptions = $state<string[]>(['vue', 'react', 'svelte', 'typescript', 'rust', 'go'])
  let tags = $state<string[]>(['svelte', 'typescript'])

  function onCreate(value: string) {
    if (!tagOptions.includes(value)) tagOptions = [...tagOptions, value]
    if (!tags.includes(value)) tags = [...tags, value]
  }
</script>

<article class="card">
  <h2>Tags — create on the fly</h2>
  <p>Type and press Enter to create new options.</p>
  <Select
    modelValue={tags}
    mode="tags"
    options={tagOptions}
    taggable
    {theme}
    placeholder="Add tags"
    onChange={(v) => (tags = v as string[])}
    {onCreate}
  />
  <pre>{JSON.stringify({ tags }, null, 2)}</pre>
</article>
